[project]
name = "no-estoy-aqui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "flet>=0.85.0",
    "flet-audio>=0.85.0",
    "mysql-connector-python>=9.7.0",
    "pillow>=12.2.0",
    "pygame>=2.6.1",
]
