[project]
name = "no-estoy-aqui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "flet>=0.85.0",
    "flet-audio>=0.85.0",
    "mysql-connector-python>=9.7.0",
    "pillow>=12.2.0",
    "pygame>=2.6.1",
    "secure-smtplib>=0.1.1",
]

[project.scripts]
# Aqui definimos el comando corto
# importante: Quitamos el prefijo "src" por que definiremos "src" como la raiz
app= "main:main"

[tool.uv]
package = true

# Esta seccion es crucial para que python vea el contenido de src como el nivel raiz
[tool.setuptools.package-dir]
""="src"
